version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile

    image: jsdrome/web-engineering

    ports:
      - 5001:1234

    environment:
      - PORT=1234
